### ISSUE TITLE
missing github.com/tjclement/pixelflut-go

### ISSUE THREAD

**Issue by pimdegroot** [tjclement/pixelflood_server#1]
I am trying to get the pixelflood server running and it seems to be missing github.com/tjclement/pixelflut-go , which isn't on github. Google didn't give a suitable replacement.

**Comment by tjclement** [comment]
I was figuring out go project structures during development, so this went a bit suboptimal. If you clone this repo into $GOPATH/github.com/tjclement/pixelflut-go, things should workfine.

Alternatively, you can rename "pixelflut-go" to "pixelflut_server" in scripts/main.go.

Let me know if you still have issues after this.
